services:
  backend:
    image: registry.gitlab.com/implo/implo-invite/backend:latest
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./data:/pb/pb_data
    networks:
      - implo-vps_proxy
      - implo-vps_watchtower
    ports:
      - "8090:8090"
    expose:
      - "8090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.implo-invites-backend.rule=Host(`invites.api.implo.at`)"
      - "traefik.http.routers.implo-invites-backend.entrypoints=websecure"
      - "traefik.http.routers.implo-invites-backend.tls.certresolver=myresolver"

  web:
    image: registry.gitlab.com/implo/implo-invite/web:latest
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        VITE_WEB_URL: https://invites.implo.at
        VITE_BACKEND_URL: https://invites.api.implo.at
    networks:
      - implo-vps_proxy
      - implo-vps_watchtower
    ports:
      - "8000:80"
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.implo-invites-web.rule=Host(`invites.implo.at`)"
      - "traefik.http.routers.implo-invites-web.entrypoints=websecure"
      - "traefik.http.routers.implo-invites-web.tls.certresolver=myresolver"

networks:
  implo-vps_proxy:
    external: true
  implo-vps_watchtower:
    external: true
